// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://digjvjghzbxxrrbuddmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZ2p2amdoemJ4eHJyYnVkZG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTM5MTYsImV4cCI6MjA2NzIyOTkxNn0.bl5vxX6QI5DLA_kHtPA97ls_lLI3brP_dWks_YZVj84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});